name: Monorepo CI

on:
  push:
  pull_request:

jobs:
  parity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run Engraving parity checks
        run: |
          ./scripts/engraving_parity_check.sh
      - name: Run Engraving audit
        run: |
          python Engraving/scripts/audit_rules_coverage.py > engraving-audit.json
          echo "Engraving audit:" && cat engraving-audit.json
      - name: Upload Engraving audit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: engraving-audit
          path: engraving-audit.json
